# Generated by Django 3.1.4 on 2020-12-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of Courses')),
                ('slug', models.SlugField(verbose_name='Shortcut')),
                ('description', models.TextField(blank=True, verbose_name='Description of Courses')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date of Begin')),
                ('imagem_course', models.ImageField(upload_to='courses/images', verbose_name='Images of Courses')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
        ),
    ]
