# Generated by Django 3.1.4 on 2020-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='imagem_course',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Images of Courses'),
        ),
    ]
